@echo off
REM Weekly LGBM retraining -- all 10 symbols, all 4 timeframes (1m/3m/5m/15m)
REM Recommended schedule: Sunday 02:00 UTC

cd /d "%~dp0.."
call .venv_312\Scripts\activate.bat

echo ============================================================
echo  CryptoAgent -- Weekly Model Retraining (10 symbols x 4 TFs)
echo  %DATE% %TIME%
echo ============================================================

REM ── 15m models ──────────────────────────────────────────────
echo.
echo === 15m MODELS ===
echo [1/10] BTC-USDC 15m...
python scripts/train_models.py --symbol BTC-USDC  --timeframe 15m --candles 18000 --splits 10 --threshold 0.003  --drop-flat --force-retrain --shap >> logs/retrain.log 2>&1
echo [2/10] ETH-USDC 15m...
python scripts/train_models.py --symbol ETH-USDC  --timeframe 15m --candles 18000 --splits 10 --threshold 0.002  --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [3/10] SOL-USDC 15m...
python scripts/train_models.py --symbol SOL-USDC  --timeframe 15m --candles 18000 --splits 10 --threshold 0.002  --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [4/10] XRP-USDC 15m...
python scripts/train_models.py --symbol XRP-USDC  --timeframe 15m --candles 18000 --splits 10 --threshold 0.002  --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [5/10] DOGE-USDC 15m...
python scripts/train_models.py --symbol DOGE-USDC --timeframe 15m --candles 18000 --splits 10 --threshold 0.002  --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [6/10] BNB-USDC 15m...
python scripts/train_models.py --symbol BNB-USDC  --timeframe 15m --candles 18000 --splits 10 --threshold 0.002  --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [7/10] SUI-USDC 15m...
python scripts/train_models.py --symbol SUI-USDC  --timeframe 15m --candles 18000 --splits 10 --threshold 0.002  --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [8/10] ENA-USDC 15m...
python scripts/train_models.py --symbol ENA-USDC  --timeframe 15m --candles 18000 --splits 10 --threshold 0.002  --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [9/10] LINK-USDC 15m...
python scripts/train_models.py --symbol LINK-USDC --timeframe 15m --candles 18000 --splits 10 --threshold 0.002  --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [10/10] ADA-USDC 15m...
python scripts/train_models.py --symbol ADA-USDC  --timeframe 15m --candles 18000 --splits 10 --threshold 0.002  --drop-flat --force-retrain >> logs/retrain.log 2>&1

REM ── 5m models ───────────────────────────────────────────────
echo.
echo === 5m MODELS ===
echo [1/10] BTC-USDC 5m...
python scripts/train_models.py --symbol BTC-USDC  --timeframe 5m --candles 18000 --splits 10 --threshold 0.001  --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [2/10] ETH-USDC 5m...
python scripts/train_models.py --symbol ETH-USDC  --timeframe 5m --candles 18000 --splits 10 --threshold 0.001  --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [3/10] SOL-USDC 5m...
python scripts/train_models.py --symbol SOL-USDC  --timeframe 5m --candles 18000 --splits 10 --threshold 0.001  --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [4/10] XRP-USDC 5m...
python scripts/train_models.py --symbol XRP-USDC  --timeframe 5m --candles 18000 --splits 10 --threshold 0.001  --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [5/10] DOGE-USDC 5m...
python scripts/train_models.py --symbol DOGE-USDC --timeframe 5m --candles 18000 --splits 10 --threshold 0.001  --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [6/10] BNB-USDC 5m...
python scripts/train_models.py --symbol BNB-USDC  --timeframe 5m --candles 18000 --splits 10 --threshold 0.001  --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [7/10] SUI-USDC 5m...
python scripts/train_models.py --symbol SUI-USDC  --timeframe 5m --candles 18000 --splits 10 --threshold 0.001  --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [8/10] ENA-USDC 5m...
python scripts/train_models.py --symbol ENA-USDC  --timeframe 5m --candles 18000 --splits 10 --threshold 0.001  --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [9/10] LINK-USDC 5m...
python scripts/train_models.py --symbol LINK-USDC --timeframe 5m --candles 18000 --splits 10 --threshold 0.001  --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [10/10] ADA-USDC 5m...
python scripts/train_models.py --symbol ADA-USDC  --timeframe 5m --candles 18000 --splits 10 --threshold 0.001  --drop-flat --force-retrain >> logs/retrain.log 2>&1

REM ── 3m models ───────────────────────────────────────────────
echo.
echo === 3m MODELS ===
echo [1/10] BTC-USDC 3m...
python scripts/train_models.py --symbol BTC-USDC  --timeframe 3m --candles 18000 --splits 10 --threshold 0.0007 --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [2/10] ETH-USDC 3m...
python scripts/train_models.py --symbol ETH-USDC  --timeframe 3m --candles 18000 --splits 10 --threshold 0.0007 --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [3/10] SOL-USDC 3m...
python scripts/train_models.py --symbol SOL-USDC  --timeframe 3m --candles 18000 --splits 10 --threshold 0.0007 --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [4/10] XRP-USDC 3m...
python scripts/train_models.py --symbol XRP-USDC  --timeframe 3m --candles 18000 --splits 10 --threshold 0.0007 --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [5/10] DOGE-USDC 3m...
python scripts/train_models.py --symbol DOGE-USDC --timeframe 3m --candles 18000 --splits 10 --threshold 0.0007 --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [6/10] BNB-USDC 3m...
python scripts/train_models.py --symbol BNB-USDC  --timeframe 3m --candles 18000 --splits 10 --threshold 0.0007 --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [7/10] SUI-USDC 3m...
python scripts/train_models.py --symbol SUI-USDC  --timeframe 3m --candles 18000 --splits 10 --threshold 0.0007 --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [8/10] ENA-USDC 3m...
python scripts/train_models.py --symbol ENA-USDC  --timeframe 3m --candles 18000 --splits 10 --threshold 0.0007 --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [9/10] LINK-USDC 3m...
python scripts/train_models.py --symbol LINK-USDC --timeframe 3m --candles 18000 --splits 10 --threshold 0.0007 --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [10/10] ADA-USDC 3m...
python scripts/train_models.py --symbol ADA-USDC  --timeframe 3m --candles 18000 --splits 10 --threshold 0.0007 --drop-flat --force-retrain >> logs/retrain.log 2>&1

REM ── 1m models ───────────────────────────────────────────────
echo.
echo === 1m MODELS ===
echo [1/10] BTC-USDC 1m...
python scripts/train_models.py --symbol BTC-USDC  --timeframe 1m --candles 18000 --splits 10 --threshold 0.0005 --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [2/10] ETH-USDC 1m...
python scripts/train_models.py --symbol ETH-USDC  --timeframe 1m --candles 18000 --splits 10 --threshold 0.0005 --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [3/10] SOL-USDC 1m...
python scripts/train_models.py --symbol SOL-USDC  --timeframe 1m --candles 18000 --splits 10 --threshold 0.0005 --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [4/10] XRP-USDC 1m...
python scripts/train_models.py --symbol XRP-USDC  --timeframe 1m --candles 18000 --splits 10 --threshold 0.0005 --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [5/10] DOGE-USDC 1m...
python scripts/train_models.py --symbol DOGE-USDC --timeframe 1m --candles 18000 --splits 10 --threshold 0.0005 --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [6/10] BNB-USDC 1m...
python scripts/train_models.py --symbol BNB-USDC  --timeframe 1m --candles 18000 --splits 10 --threshold 0.0005 --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [7/10] SUI-USDC 1m...
python scripts/train_models.py --symbol SUI-USDC  --timeframe 1m --candles 18000 --splits 10 --threshold 0.0005 --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [8/10] ENA-USDC 1m...
python scripts/train_models.py --symbol ENA-USDC  --timeframe 1m --candles 18000 --splits 10 --threshold 0.0005 --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [9/10] LINK-USDC 1m...
python scripts/train_models.py --symbol LINK-USDC --timeframe 1m --candles 18000 --splits 10 --threshold 0.0005 --drop-flat --force-retrain >> logs/retrain.log 2>&1
echo [10/10] ADA-USDC 1m...
python scripts/train_models.py --symbol ADA-USDC  --timeframe 1m --candles 18000 --splits 10 --threshold 0.0005 --drop-flat --force-retrain >> logs/retrain.log 2>&1

REM ── LSTM models (all 10 symbols) ─────────────────────────────
echo.
echo === LSTM MODELS (all 10 symbols) ===
python scripts/train_models.py --symbol BTC-USDC  --timeframe 15m --candles 18000 --splits 10 --threshold 0.002 --drop-flat --force-retrain --train-lstm >> logs/retrain.log 2>&1
python scripts/train_models.py --symbol ETH-USDC  --timeframe 15m --candles 18000 --splits 10 --threshold 0.002 --drop-flat --force-retrain --train-lstm >> logs/retrain.log 2>&1
python scripts/train_models.py --symbol SOL-USDC  --timeframe 15m --candles 18000 --splits 10 --threshold 0.002 --drop-flat --force-retrain --train-lstm >> logs/retrain.log 2>&1
python scripts/train_models.py --symbol XRP-USDC  --timeframe 15m --candles 18000 --splits 10 --threshold 0.002 --drop-flat --force-retrain --train-lstm >> logs/retrain.log 2>&1
python scripts/train_models.py --symbol DOGE-USDC --timeframe 15m --candles 18000 --splits 10 --threshold 0.002 --drop-flat --force-retrain --train-lstm >> logs/retrain.log 2>&1
python scripts/train_models.py --symbol BNB-USDC  --timeframe 15m --candles 18000 --splits 10 --threshold 0.002 --drop-flat --force-retrain --train-lstm >> logs/retrain.log 2>&1
python scripts/train_models.py --symbol SUI-USDC  --timeframe 15m --candles 18000 --splits 10 --threshold 0.002 --drop-flat --force-retrain --train-lstm >> logs/retrain.log 2>&1
python scripts/train_models.py --symbol ENA-USDC  --timeframe 15m --candles 18000 --splits 10 --threshold 0.002 --drop-flat --force-retrain --train-lstm >> logs/retrain.log 2>&1
python scripts/train_models.py --symbol LINK-USDC --timeframe 15m --candles 18000 --splits 10 --threshold 0.002 --drop-flat --force-retrain --train-lstm >> logs/retrain.log 2>&1
python scripts/train_models.py --symbol ADA-USDC  --timeframe 15m --candles 18000 --splits 10 --threshold 0.002 --drop-flat --force-retrain --train-lstm >> logs/retrain.log 2>&1

REM ── Validate ─────────────────────────────────────────────────
echo.
echo [Validate] Running BTC backtest with OOS split...
python scripts/backtest.py --symbol BTC-USDC --candles 2000 --min-confidence 25 --trailing-activation-atr 0 --oos-split 0.25 >> logs/retrain.log 2>&1

echo.
echo Retraining complete. Check logs/retrain.log for details.
echo ============================================================
